DROP TABLE USERS;
CREATE TABLE USERS (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	USERNAME	VARCHAR2(255)	NOT NULL,
	PASSWORD	VARCHAR2(255)	NOT NULL,
	ROLE		VARCHAR2(255)	NOT NULL,

	PRIMARY KEY (ID)
);

DROP SEQUENCE USER_ID_SEQ;
CREATE SEQUENCE USER_ID_SEQ
 START WITH 3
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE PROJECT;
CREATE TABLE PROJECT (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	NAME		VARCHAR2(255)	NOT NULL,
	DESCRIPTION	VARCHAR2(255)	DEFAULT NULL,

	PRIMARY KEY (ID)
);

DROP SEQUENCE PROJECT_ID_SEQ;
CREATE SEQUENCE PROJECT_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE STATUS;
CREATE TABLE STATUS (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	NAME		VARCHAR2(255)	NOT NULL,
	RANK		NUMBER(10,0)	NOT NULL,
	PROJECT_ID	NUMBER(10,0)	NOT NULL,

	PRIMARY KEY (ID),
	CONSTRAINT FK_STATUS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)

);

DROP SEQUENCE STATUS_ID_SEQ;
CREATE SEQUENCE STATUS_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE CATEGORY;
CREATE TABLE CATEGORY (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	NAME		VARCHAR2(255)	NOT NULL,
	PROJECT_ID	NUMBER(10,0)	NOT NULL,

	PRIMARY KEY (ID),
	CONSTRAINT FK_CATEGORY_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

DROP SEQUENCE CATEGORY_ID_SEQ;
CREATE SEQUENCE CATEGORY_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE TASK;
CREATE TABLE TASK (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	TITLE		VARCHAR2(255)	NOT NULL,
	DESCRIPTION	VARCHAR2(2048)	DEFAULT NULL,
	PROJECT_ID	NUMBER(10,0)	NOT NULL,
	STATUS_ID	NUMBER(10,0)	DEFAULT NULL,
	CATEGORY_ID	NUMBER(10,0)	DEFAULT NULL,
	USER_ID		NUMBER(10,0)	DEFAULT NULL,
	LAST_UPDATE	NUMBER(16,0)	NOT NULL,

	PRIMARY KEY (ID)
);

DROP SEQUENCE TASK_ID_SEQ;
CREATE SEQUENCE TASK_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;

DROP TABLE CYCLE_TIME;
CREATE TABLE CYCLE_TIME (
	
	ID			NUMBER(10,0)	NOT NULL AUTO_INCREMENT,
	TASK_ID		NUMBER(10,0)	NOT NULL,
	STATUS_ID	NUMBER(10,0)	NOT NULL,
	SPENT_TIME	NUMBER(10,0)	NOT NULL,

	PRIMARY KEY (ID),
	CONSTRAINT FK_CYCLE_TIME_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
	CONSTRAINT FK_CYCLE_TIME_STATUS FOREIGN KEY (STATUS_ID) REFERENCES STATUS(ID)
);

DROP SEQUENCE CYCLE_TIME_ID_SEQ;
CREATE SEQUENCE CYCLE_TIME_ID_SEQ
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;
